// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbNkDccTeyb8RmMHTwcAtVwclqm0NP23A',
    appId: '1:171182914435:web:9179550c83f153aecd54b6',
    messagingSenderId: '171182914435',
    projectId: 'kmis-16b02',
    authDomain: 'kmis-16b02.firebaseapp.com',
    storageBucket: 'kmis-16b02.firebasestorage.app',
    measurementId: 'G-5EMSPCZCBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Kzt8uTGIZoTqpCLsMl3jOiShAwzNx7A',
    appId: '1:171182914435:android:02ac7245fa0300dacd54b6',
    messagingSenderId: '171182914435',
    projectId: 'kmis-16b02',
    storageBucket: 'kmis-16b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-uMB9sW-tXGsKJ822x62H1z6wVAqAUD4',
    appId: '1:171182914435:ios:2f4df27967bef3cecd54b6',
    messagingSenderId: '171182914435',
    projectId: 'kmis-16b02',
    storageBucket: 'kmis-16b02.firebasestorage.app',
    iosBundleId: 'com.ksoft.ksoftsms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-uMB9sW-tXGsKJ822x62H1z6wVAqAUD4',
    appId: '1:171182914435:ios:2f4df27967bef3cecd54b6',
    messagingSenderId: '171182914435',
    projectId: 'kmis-16b02',
    storageBucket: 'kmis-16b02.firebasestorage.app',
    iosBundleId: 'com.ksoft.ksoftsms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbNkDccTeyb8RmMHTwcAtVwclqm0NP23A',
    appId: '1:171182914435:web:92985eae465dc4b7cd54b6',
    messagingSenderId: '171182914435',
    projectId: 'kmis-16b02',
    authDomain: 'kmis-16b02.firebaseapp.com',
    storageBucket: 'kmis-16b02.firebasestorage.app',
    measurementId: 'G-V1BC9DS5QZ',
  );

}